// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://zhangqi444.github.io',
  base: '/the-little-creator',

  integrations: [
    starlight({
      title: 'The Little Creator',
      description: 'A community knowledge base for youth competitive robotics — FIRST (FLL, FTC, FRC) and VEX (IQ, V5, U). For families, coaches, and teachers.',
      logo: {
        src: './src/assets/logo.svg',
        replacesTitle: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/zhangqi444/the-little-creator' },
      ],
      editLink: {
        baseUrl: 'https://github.com/zhangqi444/the-little-creator/edit/main/',
      },
      sidebar: [
        {
          label: 'Getting Started',
          items: [
            { label: 'Overview', link: '/getting-started/' },
            { label: 'Choosing a Program', link: '/getting-started/choosing-a-program/' },
            { label: 'Finding and Joining a Team', link: '/getting-started/finding-a-team/' },
            { label: 'Your First Week (all programs)', link: '/getting-started/first-steps/' },
            { label: 'What is FLL?', link: '/getting-started/what-is-fll/' },
            { label: 'What is FTC?', link: '/getting-started/what-is-ftc/' },
            { label: 'What is FRC?', link: '/getting-started/what-is-frc/' },
            { label: 'What is VEX?', link: '/getting-started/what-is-vex/' },
            { label: 'What is VEX IQ?', link: '/getting-started/what-is-vex-iq/' },
            { label: 'What is VEX V5 / VRC?', link: '/getting-started/what-is-vex-v5/' },
            { label: 'What is VEX U?', link: '/getting-started/what-is-vex-u/' },
            { label: 'Progression Guide (FLL → FTC → FRC; FLL → VEX)', link: '/getting-started/progression-guide/' },
            { label: 'Glossary', link: '/getting-started/glossary/' },
          ],
        },
        {
          label: 'Resources',
          items: [
            { label: 'Overview', link: '/resources/' },
            { label: 'FLL Resource Map', link: '/resources/fll-resource-map/' },
            { label: 'FTC Resource Map', link: '/resources/ftc-resource-map/' },
            { label: 'FRC Resource Map', link: '/resources/frc-resource-map/' },
            { label: 'VEX IQ Resource Map', link: '/resources/vex-iq-resource-map/' },
            { label: 'VEX V5/VRC Resource Map', link: '/resources/vex-v5-resource-map/' },
            { label: 'VEX U Resource Map', link: '/resources/vex-u-resource-map/' },
            { label: 'VEX Resource Map', link: '/resources/vex-resource-map/' },
            { label: 'Software & Tools', link: '/resources/software-tools/' },
            { label: 'Learning Materials', link: '/resources/learning-materials/' },
          ],
        },
        {
          label: 'Guides',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/guides/' },
            {
              label: 'Getting Started',
              collapsed: true,
              items: [
                { label: 'Forming a Team', link: '/guides/forming-a-team/' },
                { label: 'Planning Your Season', link: '/guides/season-planning/' },
                { label: 'First Four Weeks (FLL)', link: '/guides/first-four-weeks/' },
                { label: 'First Four Weeks (FTC)', link: '/guides/ftc-first-four-weeks/' },
                { label: 'First Four Weeks (FRC)', link: '/guides/frc-first-four-weeks/' },
                { label: 'First Four Weeks (VEX IQ)', link: '/guides/vex-iq-first-four-weeks/' },
                { label: 'Starting a VEX U Team', link: '/guides/vex-u-first-team/' },
                { label: 'Equipment Guide', link: '/guides/equipment-guide/' },
                { label: 'Team Funding', link: '/guides/team-funding/' },
                { label: 'Division Eligibility', link: '/guides/division-eligibility/' },
                { label: 'Registration Guide', link: '/guides/registration-guide/' },
                { label: 'Registration Reference', link: '/guides/registration-reference/' },
                { label: 'Finding Mentors', link: '/guides/finding-mentors/' },
                { label: 'Future Edition Transition', link: '/guides/future-edition-transition/' },
              ],
            },
            {
              label: 'Building & Programming',
              collapsed: true,
              items: [
                { label: 'Drivetrain Basics', link: '/guides/drivetrain-basics/' },
                { label: 'Attachment Design', link: '/guides/attachment-design/' },
                { label: 'FTC Robot Design Guide', link: '/guides/ftc-robot-design/' },
                { label: 'FRC Robot Design Guide', link: '/guides/frc-robot-design/' },
                { label: 'VEX V5 Robot Design Guide', link: '/guides/vex-v5-robot-design/' },
                { label: 'VEX IQ Robot Design Guide', link: '/guides/vex-iq-robot-design/' },
                { label: 'VEX U Robot Design Guide', link: '/guides/vex-u-robot-design/' },
                { label: 'Robot Maintenance', link: '/guides/robot-maintenance/' },
                { label: 'Robot Troubleshooting', link: '/guides/robot-troubleshooting/' },
                { label: 'FLL Robot Programming Basics (SPIKE)', link: '/guides/robot-programming-basics/' },
                { label: 'FLL Python Intermediate', link: '/guides/python-intermediate/' },
                { label: 'FTC Programming Basics', link: '/guides/ftc-programming-basics/' },
                { label: 'FRC Programming Basics', link: '/guides/frc-programming-basics/' },
                { label: 'VEX IQ Programming', link: '/guides/vex-iq-programming/' },
                { label: 'VEX V5 Programming Basics', link: '/guides/vex-v5-programming-basics/' },
                { label: 'VEX U Programming Basics', link: '/guides/vex-u-programming-basics/' },
              ],
            },
            {
              label: 'Competition Prep',
              collapsed: true,
              items: [
                { label: 'Robot Strategy', link: '/guides/robot-strategy/' },
                { label: 'Innovation Project Guide', link: '/guides/innovation-project-guide/' },
                { label: 'IP Expert Interview', link: '/guides/ip-expert-interview/' },
                { label: 'Judging Prep', link: '/guides/judging-prep/' },
                { label: 'FLL Awards', link: '/guides/fll-awards/' },
                { label: 'FTC Awards', link: '/guides/ftc-awards/' },
                { label: 'FRC Awards', link: '/guides/frc-awards/' },
                { label: 'VEX Awards', link: '/guides/vex-awards/' },
                { label: 'FLL Engineering Notebook', link: '/guides/notebook-guide/' },
                { label: 'FTC Engineering Portfolio', link: '/guides/ftc-engineering-portfolio/' },
                { label: 'FTC Judging Prep', link: '/guides/ftc-judging-prep/' },
                { label: 'FRC Judging Prep', link: '/guides/frc-judging-prep/' },
                { label: 'VEX Judging Prep', link: '/guides/vex-judging-prep/' },
                { label: 'FRC Impact Submission', link: '/guides/frc-impact-submission/' },
                { label: 'Practice Session Structure', link: '/guides/practice-session-structure/' },
                { label: 'FLL Tournament Day Checklist', link: '/guides/tournament-day-checklist/' },
                { label: 'Tournament Week Prep', link: '/guides/tournament-week-prep/' },
                { label: 'Your First FLL Tournament', link: '/guides/first-tournament-expectations/' },
                { label: 'Your First FTC Tournament', link: '/guides/first-ftc-tournament/' },
                { label: 'Your First FRC Tournament', link: '/guides/first-frc-tournament/' },
                { label: 'Your First VEX Tournament', link: '/guides/first-vex-tournament/' },
                { label: 'VEX IQ Tournament Guide (VIQRC In Depth)', link: '/guides/vex-iq-tournament/' },
                { label: 'VEX V5 Tournament Guide (V5RC In Depth)', link: '/guides/vex-v5-tournament/' },
                { label: 'After Advancing', link: '/guides/after-advancing/' },
              ],
            },
            {
              label: 'Team Culture',
              collapsed: true,
              items: [
                { label: 'Core Values Activities', link: '/guides/core-values-activities/' },
                { label: 'Gracious Professionalism', link: '/guides/gracious-professionalism/' },
                { label: 'Coaching Without Doing', link: '/guides/coaching-without-doing/' },
                { label: 'When a Kid Wants to Quit', link: '/guides/when-a-kid-wants-to-quit/' },
              ],
            },
            {
              label: 'Returning Coaches',
              collapsed: true,
              items: [
                { label: 'Second Season Guide', link: '/guides/second-season/' },
                { label: 'FTC Second Season Guide', link: '/guides/ftc-second-season/' },
                { label: 'FRC Second Season Guide', link: '/guides/frc-second-season/' },
                { label: 'VEX IQ Second Season Guide', link: '/guides/vex-iq-second-season/' },
                { label: 'VEX V5 Second Season Guide', link: '/guides/vex-v5-second-season/' },
                { label: 'VEX U Second Season Guide', link: '/guides/vex-u-second-season/' },
              ],
            },
          ],
        },
        {
          label: 'For Educators',
          items: [
            { label: 'Overview', link: '/for-educators/' },
            { label: 'FLL Curriculum Starter', link: '/for-educators/curriculum-starter/' },
            { label: 'FTC Curriculum Starter', link: '/for-educators/ftc-curriculum-starter/' },
            { label: 'FRC Curriculum Starter', link: '/for-educators/frc-curriculum-starter/' },
            { label: 'VEX IQ Curriculum Starter', link: '/for-educators/vex-iq-curriculum-starter/' },
            {{ label: 'VEX V5/VRC Curriculum Starter', link: '/for-educators/vex-v5-curriculum-starter/' },}
            { label: 'VEX U / VURC Curriculum Starter', link: '/for-educators/vex-u-curriculum-starter/' },
            { label: 'Lesson Plan Template', link: '/for-educators/lesson-plan-template/' },
            { label: 'Core Values Rubric', link: '/for-educators/core-values-rubric/' },
            { label: 'Assessment Rubric', link: '/for-educators/assessment-rubric/' },
            { label: 'Assessment Guide (All Programs)', link: '/for-educators/assessment-guide/' },
            { label: 'Differentiation Guide', link: '/for-educators/differentiation-guide/' },
            { label: 'Parent Communication', link: '/for-educators/parent-communication/' },
          ],
        },
        {
          label: 'Showcase',
          link: '/showcase/',
        },
        {
          label: 'Community',
          items: [
            { label: 'Overview', link: '/community/' },
            { label: 'Find a Team', link: '/community/find-a-team/' },
          ],
        },
      ],
      customCss: [
        './src/styles/custom.css',
      ],
    }),
  ],
});
